autoscaling:
  enabled: false

replicaCount: 1

trustProxy: true

allowOrigins:
  - https://dev.gitgud.zip

radioService:
  name: my-stupid-website-radio

terminalService:
  name: my-stupid-website-terminal

fmdService:
  name: my-stupid-website-fmd

fmd:
  tokenSecretRef: radio-service-env-dev
  tokenSecretKey: FMD_TOKEN
  tokenOptional: false

postgres:
  urlSecretRef: radio-service-env-dev
  urlSecretKey: PG_URL
  urlOptional: false
  maxConnections: 10

session:
  secretRef: "radio-service-env-dev"
  secretRefKey: SESSION_SECRET
  secretOptional: false

cache:
  ttlSeconds: 30
  memory:
    enabled: true
    maxEntries: 100

logLevel: debug

contact:
  secretRef: radio-service-env-dev
  smtp:
    hostKey: CONTACT_SMTP_HOST
    portKey: CONTACT_SMTP_PORT
    usernameKey: CONTACT_SMTP_USERNAME
    passwordKey: CONTACT_SMTP_PASSWORD
    fromAddressKey: CONTACT_FROM_ADDRESS
    toAddress: pm@gitgud.zip
  turnstile:
    secretKeyRef: TURNSTILE_SECRET_KEY
    siteKeyRef: TURNSTILE_SITE_KEY
  rateLimit:
    maxPerIp: 3
    windowSeconds: 600
    dedupeWindowSeconds: 86400
