autoscaling:
  enabled: false

replicaCount: 1

trustProxy: true

allowOrigins:
  - https://dev.gitgud.qzz.io

radioService:
  name: my-stupid-website-radio

terminalService:
  name: my-stupid-website-terminal

session:
  secretRef: "radio-service-env-dev"
  secretRefKey: SESSION_SECRET
  secretOptional: false

cache:
  ttlSeconds: 30
  memory:
    enabled: true
    maxEntries: 100
  redis:
    secretName: radio-service-env-dev
    secretKey: REDIS_URL
    optional: true

logLevel: debug
