gateway:
  enabled: true
  parentRefs:
    - name: kong
      namespace: kong
      sectionName: proxy-http-root
    - name: kong
      namespace: kong
      sectionName: proxy-http-wildcard
    - name: kong
      namespace: kong
      sectionName: proxy-https-root
    - name: kong
      namespace: kong
      sectionName: proxy-https-wildcard
  hostnames:
    - dev.gitgud.zip
  paths:
    - value: /
      type: PathPrefix
  middlewareRefs: []
  wwwRedirect:
    enabled: false
    sourceHostname: www.dev.gitgud.zip
    targetHostname: dev.gitgud.zip
    scheme: https
    statusCode: 301
    parentRefs: []
  redirects:
    - name: legacy-dev-gitgud
      sourceHostname: dev.gitgud.qzz.io
      targetHostname: dev.gitgud.zip
      scheme: https
      statusCode: 301
autoscaling:
  enabled: false
replicaCount: 1
env:
  - name: VITE_RADIO_API_BASE_URL
    value: /api/radio
  - name: VITE_TERMINAL_API_BASE_URL
    value: /api/terminal
  - name: VITE_RADIO_DEFAULT_LIMIT
    value: "200"

logLevel: debug
