gateway:
  enabled: true
  parentRefs:
    - name: traefik-gateway
      namespace: kube-system
      sectionName: web
    - name: traefik-gateway
      namespace: kube-system
      sectionName: websecure
  hostnames:
    - dev.gitgud.qzz.io
  paths:
    - value: /
      type: PathPrefix
  middlewareRefs:
    - name: my-stupid-website-dev-waf
autoscaling:
  enabled: false
replicaCount: 1
env:
  - name: VITE_RADIO_API_BASE_URL
    value: /api/radio
  - name: VITE_TERMINAL_API_BASE_URL
    value: /api/terminal
  - name: VITE_RADIO_DEFAULT_LIMIT
    value: "200"
