ingress:
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "my-stupid-website-dev-waf@kubernetescrd"
  hosts:
    - host: dev.gitgud.qzz.io
      paths:
        - path: /
          pathType: ImplementationSpecific
autoscaling:
  enabled: false
replicaCount: 1
env:
  - name: VITE_RADIO_API_BASE_URL
    value: /api/radio
  - name: VITE_TERMINAL_API_BASE_URL
    value: /api/terminal
  - name: VITE_RADIO_DEFAULT_LIMIT
    value: "200"
